language: java
jdk:
  - oraclejdk8
  - openjdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
node_js: "8"
install: 
  - ./gradlew assemble 
  - npm install -g snyk
script: 
  - ./gradlew check
  - snyk test --file=build.gradle --file=alarmclock/build.gradle --file=alarmclock/build/docker/Dockerfile
  - snyk monitor --org=mleegwt
